// design/design-system/components copy/feedback/ConfirmDialog.jsx
import React from 'react';
import { Button } from '../core/Button.jsx';

/** Destructive confirm: quit a game, cancel a room, surrender. */
export function ConfirmDialog({ title, body, confirmLabel, cancelLabel = 'Ở lại', onConfirm, onCancel }) {
  return (
    <div role="alertdialog" aria-modal="true" aria-label={title} style={{
      position: 'absolute', inset: 0, zIndex: 20, display: 'flex', alignItems: 'center',
      justifyContent: 'center', padding: 20, background: 'rgba(6,9,18,.62)'
    }}>
      <div className="panel" style={{ width: '100%', maxWidth: 360 }}>
        <h2 style={{ margin: '0 0 6px', fontSize: 'var(--text-xl)' }}>{title}</h2>
        <p style={{ margin: 0, color: 'var(--muted)', fontSize: 'var(--text-md)' }}>{body}</p>
        <div style={{ display: 'flex', gap: 8, marginTop: 18 }}>
          <Button variant="danger" onClick={onConfirm} style={{ flex: 1, minHeight: 48 }}>{confirmLabel}</Button>
          <Button onClick={onCancel} style={{ flex: 1, minHeight: 48 }}>{cancelLabel}</Button>
        </div>
      </div>
    </div>
  );
}

// apps/web/src/components/ConfirmDialog.vue
<script setup lang="ts">
import { onMounted, ref } from 'vue';

defineProps<{ title: string; body: string; confirmLabel: string }>();
const emit = defineEmits<{ confirm: []; cancel: [] }>();
const btn = ref<HTMLButtonElement | null>(null);
onMounted(() => btn.value?.focus());
</script>

<template>
  <div class="overlay" role="alertdialog" aria-modal="true" :aria-label="title" @keydown.esc="emit('cancel')">
    <div class="panel">
      <h2>{{ title }}</h2>
      <p>{{ body }}</p>
      <div class="row">
        <button ref="btn" class="btn danger" type="button" @click="emit('confirm')">{{ confirmLabel }}</button>
        <button class="btn" type="button" @click="emit('cancel')">Ở lại</button>
      </div>
    </div>
  </div>
</template>

<style scoped>
.overlay {
  position: fixed; inset: 0; z-index: 20; display: flex; align-items: center; justify-content: center;
  padding: 20px; background: rgba(6, 9, 18, .62);
}
.panel { width: 100%; max-width: 360px; }
h2 { margin: 0 0 6px; font-size: var(--text-xl); }
p { margin: 0; color: var(--muted); font-size: var(--text-md); }
.row { display: flex; gap: 8px; margin-top: 18px; }
.row .btn { flex: 1; min-height: 48px; }
.danger {
  border: 0; background: var(--bad); color: #fff; font-weight: 700;
}
</style>
