// design/design-system/components/nav/TopBar.jsx
import React from 'react';
import { Button } from '../core/Button.jsx';
import { Icon } from '../core/Icon.jsx';

/** App header: brand (home), accumulated score, dark + sound toggles. */
export function TopBar({ totalScore = 0, dark = false, sound = true, onHome, onToggleDark, onToggleSound }) {
  return (
    <header style={{
      display: 'flex', alignItems: 'center', gap: 'var(--sp-2)', padding: 'var(--sp-2) var(--sp-4)',
      borderBottom: '1px solid var(--line)', background: 'var(--panel)',
      backdropFilter: 'blur(var(--glass-blur))', WebkitBackdropFilter: 'blur(var(--glass-blur))'
    }}>
      <h1 style={{ flex: 1, minWidth: 0, margin: 0, fontSize: 'var(--text-xl)', fontWeight: 800, lineHeight: 1.35 }}>
        <button type="button" aria-label="Về trang chủ" onClick={onHome} style={{
          display: 'flex', alignItems: 'center', gap: 'var(--sp-2)', border: 0,
          background: 'none', padding: 0, font: 'inherit', cursor: 'pointer'
        }}>
          <span aria-hidden="true" style={{ fontSize: 24, filter: 'drop-shadow(0 2px 6px var(--card-back-glow))' }}>🃏</span>
          <span style={{
            background: 'linear-gradient(100deg, var(--accent), var(--accent-2))',
            WebkitBackgroundClip: 'text', backgroundClip: 'text', color: 'transparent',
            whiteSpace: 'nowrap', fontSize: 'clamp(17px, 5.2vw, 22px)'
          }}>Memory Match</span>
        </button>
      </h1>
      <span title={`Tổng điểm tích lũy: ${totalScore}`} style={{
        fontSize: 'var(--text-sm)', fontWeight: 700, color: 'var(--muted)', fontVariantNumeric: 'tabular-nums',
        padding: '4px 10px', borderRadius: 'var(--r-full)', background: 'var(--accent-soft)', whiteSpace: 'nowrap', flexShrink: 0
      }}>⭐ {totalScore}</span>
      <Button aria-label={dark ? 'Chuyển sang nền sáng' : 'Chuyển sang nền tối'} onClick={onToggleDark}>
        <Icon name={dark ? 'sun' : 'moon'} size={20} />
      </Button>
      <Button aria-pressed={sound} aria-label="Bật/tắt âm thanh" onClick={onToggleSound}>
        <Icon name={sound ? 'volume-2' : 'volume-x'} size={20} />
      </Button>
    </header>
  );
}

// apps/web/src/components/TopBar.vue
<script setup lang="ts">
import { Moon, Sun, Volume2, VolumeX } from 'lucide-vue-next';

defineProps<{ dark: boolean; sound: boolean; totalScore: number }>();
defineEmits<{ 'toggle-dark': []; 'toggle-sound': []; home: [] }>();
</script>

<template>
  <header class="topbar">
    <h1>
      <button class="brand" type="button" aria-label="Về trang chủ" @click="$emit('home')">
        <span class="logo" aria-hidden="true">🃏</span><span class="name">Memory Match</span>
      </button>
    </h1>
    <span class="total" :title="`Tổng điểm tích lũy: ${totalScore}`">⭐ {{ totalScore }}</span>
    <button class="btn" :aria-label="dark ? 'Chuyển sang nền sáng' : 'Chuyển sang nền tối'" type="button" @click="$emit('toggle-dark')">
      <Sun v-if="dark" :size="20" />
      <Moon v-else :size="20" />
    </button>
    <button class="btn" :aria-pressed="sound" aria-label="Bật/tắt âm thanh" type="button" @click="$emit('toggle-sound')">
      <Volume2 v-if="sound" :size="20" />
      <VolumeX v-else :size="20" />
    </button>
  </header>
</template>

<style scoped>
.topbar {
  display: flex; align-items: center; gap: var(--sp-2);
  padding: var(--sp-2) var(--sp-4);
  border-bottom: 1px solid var(--line);
  background: var(--panel);
  backdrop-filter: blur(14px);
  -webkit-backdrop-filter: blur(14px);
}
h1 { flex: 1; margin: 0; font-size: var(--text-xl); font-weight: 800; }
.brand {
  display: flex; align-items: center; gap: var(--sp-2);
  border: 0; background: none; padding: 0;
  font: inherit; cursor: pointer;
}
.logo { font-size: 24px; filter: drop-shadow(0 2px 6px var(--card-back-glow)); }
.name {
  background: linear-gradient(100deg, var(--accent), var(--accent-2));
  -webkit-background-clip: text;
  background-clip: text;
  color: transparent;
}
.total {
  font-size: var(--text-sm); font-weight: 700; color: var(--muted);
  font-variant-numeric: tabular-nums;
  padding: 4px 10px; border-radius: var(--r-full);
  background: var(--accent-soft);
}
</style>
