// apps/web/src/components/HudBar.vue
<script setup lang="ts">
import { computed } from 'vue';
import { clock } from '@/lib/format';

const props = defineProps<{
  score: number;
  moves: number;
  matched: number;
  totalPairs: number;
  combo: number;
  elapsed: number;
  timeLeft: number | null;
  movesLeft: number | null;
  lives: number | null;
  levelId?: number;
}>();

defineEmits<{ quit: [] }>();

const timeText = computed(() => clock(props.timeLeft ?? props.elapsed));
const timeLabel = computed(() => (props.timeLeft === null ? 'Thời gian' : 'Còn lại'));
const urgent = computed(() => props.timeLeft !== null && props.timeLeft <= 10);
</script>

<template>
  <div class="hud panel">
    <div v-if="levelId" class="stat"><span>Màn</span><b>{{ levelId }}</b></div>
    <div class="stat"><span>Điểm</span><b>{{ score }}</b></div>
    <div class="stat"><span>Lượt</span><b>{{ moves }}<i v-if="movesLeft !== null">/{{ moves + movesLeft }}</i></b></div>
    <div class="stat"><span>Cặp</span><b>{{ matched }}/{{ totalPairs }}</b></div>
    <div class="stat" :class="{ urgent }"><span>{{ timeLabel }}</span><b>{{ timeText }}</b></div>
    <div class="stat combo" :class="{ hot: combo >= 1.5, max: combo >= 2 }">
      <span>Combo</span><b :key="combo">x{{ combo }}</b>
    </div>
    <div v-if="lives !== null" class="stat"><span>Mạng</span><b>{{ '❤️'.repeat(Math.max(0, lives)) || '—' }}</b></div>
    <button class="btn quit" aria-label="Thoát về menu" type="button" @click="$emit('quit')">✕</button>
  </div>
</template>

<style scoped>
.hud { display: flex; align-items: center; gap: 10px; flex-wrap: wrap; padding: 8px 10px; }
.stat { display: flex; flex-direction: column; min-width: 52px; }
.stat span { font-size: 11px; text-transform: uppercase; color: var(--muted); }
.stat b { font-variant-numeric: tabular-nums; }
.stat b i { font-style: normal; color: var(--muted); font-weight: 400; font-size: 13px; }
.stat.urgent b { color: var(--bad); animation: blink 1s steps(2) infinite; }
@keyframes blink { 50% { opacity: .35; } }
.combo b { display: inline-block; animation: bump .3s cubic-bezier(.3, 1.6, .5, 1); }
.combo.hot b { color: var(--warn); }
.combo.max b {
  color: var(--gold);
  text-shadow: 0 0 10px color-mix(in srgb, var(--gold) 60%, transparent);
}
@keyframes bump { 40% { transform: scale(1.35); } }
.quit { margin-left: auto; }
</style>

// design/design-system/components copy/game/HudBar.jsx
import React from 'react';
import { Button } from '../core/Button.jsx';
import { Icon } from '../core/Icon.jsx';

const clock = (s) => `${Math.floor(Math.max(0, Math.floor(s)) / 60)}:${String(Math.max(0, Math.floor(s)) % 60).padStart(2, '0')}`;

function Stat({ label, value, sub, tone }) {
  return (
    <div style={{ display: 'flex', flexDirection: 'column', minWidth: 52 }}>
      <span style={{ fontSize: 'var(--text-xs)', textTransform: 'uppercase', letterSpacing: '.06em', color: 'var(--muted)', fontWeight: 700 }}>{label}</span>
      <b style={{
        fontVariantNumeric: 'tabular-nums', fontFamily: 'var(--font-display)',
        fontSize: 'var(--text-lg)', lineHeight: 1.2, color: tone || 'inherit',
        textShadow: tone === 'var(--gold)' ? '0 0 10px color-mix(in srgb, var(--gold) 60%, transparent)' : undefined
      }}>
        {value}{sub && <i style={{ fontStyle: 'normal', color: 'var(--muted)', fontWeight: 400, fontSize: 13 }}>{sub}</i>}
      </b>
    </div>
  );
}

/** In-game stat bar on a glass panel. Multiplayer hides score/moves/combo. */
export function HudBar({
  score = 0, moves = 0, matched = 0, totalPairs = 0, combo = 1,
  elapsed = 0, timeLeft = null, movesLeft = null, lives = null,
  levelId, multiplayer = false, onQuit
}) {
  const urgent = timeLeft !== null && timeLeft <= 10;
  const comboTone = combo >= 2 ? 'var(--gold)' : combo >= 1.5 ? 'var(--warn)' : undefined;
  return (
    <div className="panel" style={{ display: 'flex', alignItems: 'center', gap: 10, flexWrap: 'wrap', padding: '8px 12px' }}>
      {levelId ? <Stat label="Màn" value={levelId} /> : null}
      {!multiplayer && <Stat label="Điểm" value={score} />}
      {!multiplayer && <Stat label="Lượt" value={moves} sub={movesLeft !== null ? `/${moves + movesLeft}` : undefined} />}
      <Stat label="Cặp" value={`${matched}/${totalPairs}`} />
      <Stat label={timeLeft === null ? 'Thời gian' : 'Còn lại'} value={clock(timeLeft ?? elapsed)} tone={urgent ? 'var(--bad)' : undefined} />
      {!multiplayer && <Stat label="Combo" value={`x${combo}`} tone={comboTone} />}
      {lives !== null && <Stat label="Mạng" value={'❤️'.repeat(Math.max(0, lives)) || '—'} />}
      <Button aria-label="Thoát về menu" onClick={onQuit} style={{ marginLeft: 'auto' }}><Icon name="x" size={20} /></Button>
    </div>
  );
}
